version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: 1000:1000
    network_mode: "host"
    ports:
      - "8096:8096" # HTTP port (host:container)
    volumes:
      - ./config:/config
      - ./jellyfin/cache:/cache
      # - /path/to/media:/media
      - /data/seafile-fuse/cddibble@gmail.com/c317523f-253f-4d52-89d9-366e81201395_Movies:/media
      - /data/seafile-fuse/cddibble@gmail.com/c98f4e77-83dc-47d0-8c9a-2cc436c7a44b_Music:/music
      - /data/seafile-fuse/cddibble@gmail.com/eacd146d-30cd-4fa3-8956-5f689fa7ed5b_eBooks:/ebooks
      - /data/seafile-fuse/cddibble@gmail.com/8c6f622b-d895-4676-86cc-3e5bdd13e619_Shows/:/shows
      - /xmltvdata/xmltv.xml:/xmltvdata/xmltv.xml
      # - /path/to/media2:/media2:ro
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 4G
        reservations:
          cpus: "0.01"
          memory: 20M
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.tuerto.net
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
