version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./jellyfin/cache:/cache
      # - /path/to/media:/media
      - /data/seafile-fuse/cddibble@gmail.com/c317523f-253f-4d52-89d9-366e81201395_Movies:/media
      # - /path/to/media2:/media2:ro
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
