# https://github.com/docker/awesome-compose/tree/master/nextcloud-postgres
version: "3.0"
services:
  nextcloud:
    image: nextcloud:apache
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=nextcloud_postgres
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=nc.tuerto.net
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nc.tuerto.net
    networks:
      - redisnet
      - dbnet
    ports:
      - 8080:80
    restart: always
    volumes:
      - nc_data:/var/www/html
      - /data/seafile-fuse/cddibble@gmail.com/032fa411-2033-4f08-8c41-c50dd0830067_Photos:/var/www/html/seafile-fuse/cddibble@gmail.com/Photos:shared
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    restart: always
    networks:
      - redisnet
    expose:
      - 6379

  db:
    image: postgres:alpine
    hostname: nextcloud_postgres
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: always
    networks:
      - dbnet
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432

  # this should run background jos but I have found it doesnt work: https://github.com/nextcloud/docker/issues/1740
  # cron:
  #   image: nextcloud:apache
  #   restart: always
  #   user: www-data
  #   environment:
  #     - REDIS_HOST=redis
  #     - POSTGRES_HOST=nextcloud_postgres
  #     - POSTGRES_PASSWORD=nextcloud
  #     - POSTGRES_DB=nextcloud
  #     - POSTGRES_USER=nextcloud
  #   volumes:
  #     - nc_data:/var/www/html
  #   entrypoint: /cron.sh
  #   depends_on:
  #     - db
  #     - redis
volumes:
  db_data:
  nc_data:
networks:
  dbnet:
  redisnet:
